layout_spectrum: 0.2846639
typography_spectrum: 0.4608949
color:
  saturation: 0.9682935
  lightness: 0.8845783
  brandStrength: 0.5214823
  brandColors:
    - '#FFFFFF'
    - '#141416'
    - '#42454E'
    - '#9B9FAB'
    - '#6E7482'
  rhythmicContrast: 0.2379169
name: KitRinçage
