collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9682935
  brandStrength: 0.5214823
  lightness: 0.9758323
  brandColors:
    - '#FFFFFF'
    - '#141416'
    - '#42454E'
    - '#9B9FAB'
    - '#6E7482'
  rhythmicContrast: 0.2379169
typography_spectrum: 0.4452202
layout_spectrum: 0
name: KitRinçage
